apiVersion: v1
kind: Namespace
metadata:
  name:  bu-wksp-pam-dm-m4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wksp-pam-dm-m4
  name: wksp-pam-dm-m4
  namespace: bu-wksp-pam-dm-m4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wksp-pam-dm-m4
  template:
    metadata:
      labels:
        app: wksp-pam-dm-m4
    spec:
      containers:
      - name: wksp-pam-dm-m4-service
        image: quay.io/osevg/workshopper:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
        - name: CONTENT_URL_PREFIX
          value: "https://raw.githubusercontent.com/RedHat-Middleware-Workshops/rhpam-rhdm-workshop-v1m4-guides/master/"
        - name: WORKSHOPS_URLS
          value: "https://raw.githubusercontent.com/RedHat-Middleware-Workshops/rhpam-rhdm-workshop-v1m4-guides/master/_rhpam-rhdm-workshop-module4.yml"
        - name: LOG_TO_STDOUT
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: wksp-pam-dm-m4-service
  namespace: bu-wksp-pam-dm-m4
  labels:
    app: wksp-pam-dm-m4-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: wksp-pam-dm-m4
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: wksp-pam-dm-m4-route
    namespace: bu-wksp-pam-dm-m4
    labels:
      app: wksp-pam-dm-m4
spec:
  port:
    targetPort: http
  to:
      kind: Service
      name: wksp-pam-dm-m4-service

